<?php
$aAllProductData = $this->oAllProductData;
$iAllProductData = count($aAllProductData);
$iAvailableAllProductData = 0;
for($i=0;$i<$iAllProductData;$i++){
	if($aAllProductData[$i]['pay_status']==0)$iAvailableAllProductData++;
}
?>


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headMeta(); ?>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php
	/* print html title string and avoid cross-site scripting attack */
	/* $this->headTitle()	-> pointer on html head title */
	/* $this->escape()		-> avoid cross-site scripting attack (every time when you print out)*/
	/* $this->translate()	-> translate variable to text string */
	//echo $this->headTitle($this->escape($this->translate('ttl_application')));
	echo $this->headTitle($this->escape('Electronic Bidding System'));
	/**/
	?>
	<base
		href="<?php
	        if (empty($_SERVER['HTTPS'])) {
	            echo 'http://';
	        } else {
	            echo 'https://';
	        }
	        /* $this->baseUrl()		-> declare base url default or start directory path */
	        echo $_SERVER['HTTP_HOST'].$this->baseUrl();
	        /**/
	        ?>" />
	<link rel="shortcut icon"
		href="<?php echo $this->baseUrl('images/icon/favicon-icon.ico'); ?>" />
	<link rel="apple-touch-icon-precomposed" sizes="512x512"
		href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
	<!--
	    	iPhone and iPad Shortcuts
	    	For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: 57x57
	    	For first-generation iPad: 72x72
	    	For iPhone 4 with high-resolution Retina display: 114x114
		-->
	<!--
	    	<link rel="apple-touch-icon" href="<?php // echo $this->baseUrl('images/apple-touch-icon.png'); ?>" />
		    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="512x512" href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
		-->
	<?php
	/* $this->headLink()-> pointer on html head link for style sheet declare (CSS) */
	echo $this->headLink()
	->appendStylesheet($this->baseUrl('css/jquery-ui.css'))
	->appendStylesheet($this->baseUrl('css/bootstrap.css'))
	->appendStylesheet($this->baseUrl('css/font-awesome.css'))
	->appendStylesheet($this->baseUrl('css/select2.css'))
	->appendStylesheet($this->baseUrl('css/style.css'))
	->appendStylesheet($this->baseUrl('css/jquery.dataTables.css'));
	/* define browser */
	// ->appendStylesheet($this->baseUrl('css/ie.css'), null, 'gte IE 7')
	/**/
	?>

</head>

<body>
<div class="row">
<div class="col-md-1">&nbsp</div>
<div class="col-md-11">
	<p><h3>รายการสินค้าแบบซื้อ จำนวน <?php echo $iAvailableAllProductData?> รายการ</h3></p>
</div>
</div>
<div class="row">
	<div class="col-md-7">&nbsp</div>
	<div class="col-md-5" align="right">
		<div class="col-md-6">
				<form  id="loginForm" name="loginForm"
					action="<?php echo $this->url(array(
								'controller' => 'index',
								'action' => 'product-list'), null, true); ?>"
					enctype="application/x-www-form-urlencoded" method="post">
					<button class="btn btn-success" type="submit">
					<span class="glyphicon glyphicon-th-large"></span> แสดงสินค้าทั้งหมด</button>
				</form>
		</div>
		<div class="col-md-6">
				<form  id="loginForm" name="loginForm"
					action="<?php echo $this->url(array(
								'controller' => 'index',
								'action' => 'bid-product-list'), null, true); ?>"
					enctype="application/x-www-form-urlencoded" method="post">
					<button class="btn btn-success" type="submit">
					<span class="glyphicon glyphicon-th-large"></span> แสดงแต่สินค้าแบบประมูล </button>
				</form>
		</div>
	</div>
</div>
<br /><br />
<div id="view-content">
	<div class="tableProduct">
	<style>
		table{   			
   			 width:80%;     			 
   			 margin-top: 10px;
   			 
   		}
   		
		td.left{
			width:30%;
			padding: 15px;	
		}
	
		td.right{
			width:70%;
			padding: 15px;	
			vertical-align: top;
			margin-bottom: 50px;
		}
	
		div.img{
			border: 1px solid #C0C0C0  ;
		}
	
		h5{
			color: #909090; 
		}
	
		tr{
			border: 1px solid #C0C0C0;
			border-top-style: none;  			
			border-left: none;
			border-right-style: none;
		}
		
		tr.space{
		border:none;
		}
	
	</style>
	
	<table align="center" >
	<?php
$iCounter = 0; 
for($i=0;$i<$iAllProductData;$i++)
{if($aAllProductData[$i]['pay_status']==0){
$iCounter++;
?>
  		<tr>
    		<td class="left">
    			<div class="img" align="center">
	    			<div class="row">
		    			<img src="../images/scg_icon.png" width="200px" height ="250px" >
	    			</div>	
	    			<div class="row">
	    				<?php print("จำนวนสินค้า : ".$aAllProductData[$i]['quantity']." ชิ้น")?>
	    			</div>
    		 	</div>
    		 	<br>
  
				<div class="buttonBuyout" align="center">
					<form  id="loginForm" name="loginForm"
						action="<?php echo $this->url(array(
									'controller' => 'product',
									'action' => 'product-buyout'), null, true); ?>"
						enctype="application/x-www-form-urlencoded" method="post">
						<input type="hidden" name="id" value=<?php echo $aAllProductData[$i]['id']?> />
						<button class="btn btn-success" type="submit">
						<span class="glyphicon glyphicon-th-large"></span> ดูข้อมูลสินค้าแบบเต็ม </button>
						</form>
				</div>
							  
    		</td>
    		
    		<td class="right">
    		
    		<p><h3><?php print($iCounter.") ".$aAllProductData[$i]['product_name'])?> </h3></p>
    		<p><h5><?php print($aAllProductData[$i]['properties'])?></h5></p>
    		<br>
    		<p><h3><?php print("ราคา : ".$aAllProductData[$i]['showPrice']." บาท")?> 
    		</h3></p>
    		<br>
    		<br>
    		<div class="row">
    			<div class="buttonBuyout">
					<form id="loginForm" name="loginForm"
						action="<?php echo $this->url(array(
									'controller' => 'product',
									'action' => 'buy'), null, true); ?>"
						enctype="application/x-www-form-urlencoded" method="post">
						<input type="hidden" name="id" value=<?php echo $aAllProductData[$i]['id']?> />
						<button class="btn btn-success" type="submit">
						<span class="glyphicon glyphicon-ok"></span>ซื้อ</button>
					</form>
				</div>
			
    		</div>
    		
    		</p>
    		<br> 
    		 
    			 	
  
    		</td>
  		</tr>
  		
  		<tr class="space">
  		<td><br></td>
  		</tr>
  		
  		<?php }} ?>
  		
  		
  	</table>
 
	</div>
	
	
	
	
</div>

</body>
<?php
	/* $this->headScript()	-> pointer end of html for include script files (JS) */
	/* reverse order because of prepend! */
	echo $this->headScript()
	->prependFile($this->baseUrl('js/bootstrap.js'))
	->prependFile($this->baseUrl('js/jquery-1.9.0.js'));
	/**/
?>