	<?php
/**
 * Global layout
 *
 * handle all outer content for all view
 *
 * @copyright  802 Digital Media Co. Ltd.
 * @since      File available since Release 1.0
 */
?>
<?php 
/* Initialize specification standard for this page [Bootstrap.php] */
/* IMPORTANT! -> set up every time */
echo $this->doctype();
/**/
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headMeta(); ?>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php
	/* print html title string and avoid cross-site scripting attack */
	/* $this->headTitle()	-> pointer on html head title */
	/* $this->escape()		-> avoid cross-site scripting attack (every time when you print out)*/
	/* $this->translate()	-> translate variable to text string */
	//echo $this->headTitle($this->escape($this->translate('ttl_application')));
	echo $this->headTitle($this->escape('Warehouse Management System'));
	/**/
	?>
	<base
		href="<?php
	        if (empty($_SERVER['HTTPS'])) {
	            echo 'http://';
	        } else {
	            echo 'https://';
	        }
	        /* $this->baseUrl()		-> declare base url default or start directory path */
	        echo $_SERVER['HTTP_HOST'].$this->baseUrl();
	        /**/
	        ?>" />
	<link rel="shortcut icon"
		href="<?php echo $this->baseUrl('images/icon/favicon-icon.ico'); ?>" />
	<link rel="apple-touch-icon-precomposed" sizes="512x512"
		href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
	<!--
	    	iPhone and iPad Shortcuts
	    	For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: 57x57
	    	For first-generation iPad: 72x72
	    	For iPhone 4 with high-resolution Retina display: 114x114
		-->
	<!--
	    	<link rel="apple-touch-icon" href="<?php // echo $this->baseUrl('images/apple-touch-icon.png'); ?>" />
		    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="512x512" href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
		-->
	<?php
	/* $this->headLink()-> pointer on html head link for style sheet declare (CSS) */
	echo $this->headLink()
	->appendStylesheet($this->baseUrl('css/jquery-ui.css'))
	->appendStylesheet($this->baseUrl('css/bootstrap.css'))
	->appendStylesheet($this->baseUrl('css/font-awesome.css'))
	->appendStylesheet($this->baseUrl('css/select2.css'))
	->appendStylesheet($this->baseUrl('css/style.css'))
	->appendStylesheet($this->baseUrl('css/parsley.css'))
	->appendStylesheet($this->baseUrl('css/jquery.dataTables.css'));
	/* define browser */
	// ->appendStylesheet($this->baseUrl('css/ie.css'), null, 'gte IE 7')
	/**/
	?>

</head>
<body>


<?php
$iFlashmsg = 0; 
if(isset($this->aFlashMsg[0]['flashStatus'])){
	$iFlashMsg = $this->aFlashMsg [0] ['flashStatus'];
}
?>	
	
<input type="hidden" id="flash_msg" name="flash_msg"
		value="<?php echo $iFlashMsg; ?>">

	
	
	<div id="layout" class="container" style="background-color: #DDDDFF; height: 570px; width: 1200px; margin-top: 25px;
	background-image: url('../images/login_background_3.jpg');
	background-size: 100%;
">
	<div id="index" style="padding-top: 52px;">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-center">
				<div class="well" style="background-color:#F4C747;">
					<div style="position: relative; top: 0px; left: 160px;
 						width: 200px; height: 60px;
						background-size: 100%;
						">
					</div>
	
	
	
	
	
	<form data-parsley-validate class="form-horizontal" id="testForm"
		name="testForm" method="post"
		action="<?php
		
		echo $this->url ( array (
				'controller' => 'system',
				'action' => 'change-password' 
		), null, true );
		?>"
		enctype="application/x-www-form-urlencoded">

			<input type="hidden" id="id" name="id"
		value="<?php echo $this->id; ?>" />
		
		<fieldset>

			<!-- Form Name -->
			<div class="form-group">
				<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="password">รหัสผ่านใหม่</label>
				<div class="col-md-4">
					<input id="password" name="password" class="form-control input-md"
						type="password" maxlength='20' required
						data-parsley-length="[8, 20]"
						data-parsley-length-message="password ต้องมีความยาวระหว่าง 8-20 ตัวอักษร" />

				</div>
			</div>

			<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="passwordConfirm">ยืนยันรหัสผ่านใหม่</label>
				<div class="col-md-4">
					<input id="passwordConfirm" name="passwordConfirm"
						class="form-control input-md" type="password" maxlength='20'
						required data-parsley-length="[8, 20]"
						data-parsley-equalto="#password"
						data-parsley-length-message="password ต้องมีความยาวระหว่าง 8-20 ตัวอักษร"
						data-parsley-equalto-message="password ไม่ตรงกัน" />

				</div>
			</div>
			</div>
			
			
			
			
						<!-- Button (Double) -->
			<div class="form-group">
				<label class="col-md-3 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-success" type="submit">
						<span class="glyphicon glyphicon-ok"></span> ยืนยัน
					</button>
				</div>
			</div>
		</fieldset>
		<div class=col-md-4></div>

	</form>
	
		<div class="modal fade" id="alertModal" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header text-center">
					<h4 class="modal-title" id="alertModalLabel">default</h4>
				</div>
				<div class="modal-body text-center">
					<button type="button" class="btn btn-default" data-dismiss="modal">ตกลง</button>
				</div>
			</div>
		</div>
	</div>

	
	<?php
$this->headScript ()->appendScript ( '

		var flash_msg;


		$(document).ready(function () {

	
			// get flash messenger value
			flash_msg = $("#flash_msg").val();
		
			switch(parseInt(flash_msg)) {
				case 901 :
					$("#alertModalLabel").html("รูปแบบของ password ต้องประกอบด้วยตัวเลข ตัวพิมพ์ใหญ่ และตัวพิมพ์เล็กอย่างน้อย 1 ตัวอักษร");
					$("#alertModal").modal("show");
					break;

				case 900 :
					$("#alertModalLabel").html("password ไม่ตรง");
					$("#alertModal").modal("show");
					break;

				
			}
		});

		
' );
?>
	
	
	<?php
	/* $this->headScript()	-> pointer end of html for include script files (JS) */
	/* reverse order because of prepend! */
	echo $this->headScript()
	->prependFile($this->baseUrl('js/bootstrap.js'))
	->prependFile($this->baseUrl('js/parsley.min.js'))
	->prependFile($this->baseUrl('js/jquery-1.9.0.js'));
	
	/**/
	?>
	<?php 
	$this->headScript()
		->appendScript('
			$(document).ready(function () {
				$("#myTab a").click(function (e) {
					e.preventDefault()
					$(this).tab("show")
				})
			});
				 
		');
	?>
</body>
</html>
	