<?php
/**
 * Global layout
 *
 * handle all outer content for all view
 *
 * @copyright  802 Digital Media Co. Ltd.
 * @since      File available since Release 1.0
 */
?>
<?php 
/* Initialize specification standard for this page [Bootstrap.php] */
/* IMPORTANT! -> set up every time */
echo $this->doctype();
/**/
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headMeta(); ?>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php
	/* print html title string and avoid cross-site scripting attack */
	/* $this->headTitle()	-> pointer on html head title */
	/* $this->escape()		-> avoid cross-site scripting attack (every time when you print out)*/
	/* $this->translate()	-> translate variable to text string */
	//echo $this->headTitle($this->escape($this->translate('ttl_application')));
	echo $this->headTitle($this->escape('Warehouse Management System'));
	/**/
	?>
	<base
		href="<?php
	        if (empty($_SERVER['HTTPS'])) {
	            echo 'http://';
	        } else {
	            echo 'https://';
	        }
	        /* $this->baseUrl()		-> declare base url default or start directory path */
	        echo $_SERVER['HTTP_HOST'].$this->baseUrl();
	        /**/
	        ?>" />
	<link rel="shortcut icon"
		href="<?php echo $this->baseUrl('images/icon/favicon-icon.ico'); ?>" />
	<link rel="apple-touch-icon-precomposed" sizes="512x512"
		href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
	<!--
	    	iPhone and iPad Shortcuts
	    	For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: 57x57
	    	For first-generation iPad: 72x72
	    	For iPhone 4 with high-resolution Retina display: 114x114
		-->
	<!--
	    	<link rel="apple-touch-icon" href="<?php // echo $this->baseUrl('images/apple-touch-icon.png'); ?>" />
		    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="512x512" href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
		-->
	<?php
	/* $this->headLink()-> pointer on html head link for style sheet declare (CSS) */
	echo $this->headLink()
	->appendStylesheet($this->baseUrl('css/jquery-ui.css'))
	->appendStylesheet($this->baseUrl('css/bootstrap.css'))
	->appendStylesheet($this->baseUrl('css/font-awesome.css'))
	->appendStylesheet($this->baseUrl('css/select2.css'))
	->appendStylesheet($this->baseUrl('css/style.css'))
	->appendStylesheet($this->baseUrl('css/jquery.dataTables.css'));
	/* define browser */
	// ->appendStylesheet($this->baseUrl('css/ie.css'), null, 'gte IE 7')
	/**/
	?>

</head>
<body>

<?php 
	// set data default variable
	$iFlashMsg = 0;
	
	// check validation callback
	if (count($this->aFlashMsg) > 0) {
		$aFlashMsg		= $this->aFlashMsg;
		$iFlashMsg		= $aFlashMsg[0]['status'];
	}
?>
<input type="hidden" id="flash_msg" name="flash_msg"
	value="<?php echo $iFlashMsg; ?>" />
	
<div id="layout" class="container" style="background-color: #DDDDFF; height: 570px; width: 1200px; margin-top: 25px;
	background-image: url('../images/login_background_3.jpg');
	background-size: 100%;
">
	<div id="index" style="padding-top: 52px;">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 text-center">
				<div class="well" style="background-color:#F4C747;">
					<div style="position: relative; top: 0px; left: 160px;
 						width: 200px; height: 60px;
						background-size: 100%;
						">
					</div>
					<form id="loginForm" name="loginForm"
						action="<?php echo $this->url(array(
									'controller' => 'system',
									'action' => 'login'), null, true); ?>"
						enctype="application/x-www-form-urlencoded" method="post">
						<h2 class="form-signin-heading" style="color: #515151;">Electronic Bidding System</h2>
						<br>
						<input type="text" name="sUsername" class="input-block-level"
							placeholder="Username" required />
						<input type="password" name="sPassword" class="input-block-level"
							placeholder="Password" required />
						&nbsp
						<input type="submit" class="btn btn btn-success"
							value="ล็อคอินเข้าสู่ระบบ" />
					</form>
						<div class="row">&nbsp</div>
						<div class="row">
						<div class="link" style="position:absolute;right:30px;">
							<a href="/index/reset-password-form">ลืมรหัสผ่าน</a>
						</div>
						</div>
						<div class="row">&nbsp</div>
						<div class="row">
						<div class="link" style="position:absolute;right:30px;">
							<a href="/index/product-list">เข้าใช้งานเวปไซต์แบบผู้เยี่ยมชม</a>
						</div>
						</div>
						<div class="row">&nbsp</div>
						<div class="row">
						<div class="link" style="position:absolute;right:30px;">
							<a href="/index/register">ต้องการสมัครสมาชิกคลิกที่นี่</a>
						</div>
						</div>
						<div class="row">&nbsp</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
	    <div class="modal-content">
		  	<div class="modal-header text-center">
		     	<h4 class="modal-title" id="alertModalLabel">default</h4>
		 	</div>
		 	<div class="modal-body text-center">
	        	<button type="button" class="btn btn-default" data-dismiss="modal">ตกลง</button>
		   	</div>
	 	</div>
	</div>
</div>

<?php
$this->headScript()->appendScript('

		var flash_msg;

		$(document).ready(function () {

			// get flash messenger value
			flash_msg = $("#flash_msg").val();

			switch(parseInt(flash_msg))
			{
				
				case 999 : 
					$("#alertModalLabel").html("บัญชีของท่านถูกระงับการใช้งาน");
					$("#alertModal").modal("show"); 
					break;

				case 699 : 
					$("#alertModalLabel").html("ทำการเปลี่ยนรหัสผ่านสำเร็จ");
					$("#alertModal").modal("show"); 
					break;
								

				case 700 : 
					$("#alertModalLabel").html("ส่งอีเมล์เพื่อให้ทำการเปลี่ยนรหัสผ่านแล้ว");
					$("#alertModal").modal("show"); 
					break;
				case 1000 : 
					$("#alertModalLabel").html("ยืนยันบัญสำเร็จสามารถเข้าสู่ระบบโดยใช้ชื่อบัญชีที่ยืนยันได้ทันที");
					$("#alertModal").modal("show"); 
					break;
				case 901 : 
					$("#alertModalLabel").html("คุณกรอกข้อมูลไม่ครบถ้วน");
					$("#alertModal").modal("show"); 
					break;
				case 902 :
					$("#alertModalLabel").html("ระบบไม่สามารถทำงานต่อไปได้ เนื่องจากคุณกำลังพยายามแทรกแทรงการทำงานของระบบ");
					$("#alertModal").modal("show"); 
					break;
				case 3 : 
					$("#alertModalLabel").html("หลังจากตรวจสอบแล้วข้อมูลบางอย่างของคุณไม่ถูกต้อง");
					$("#alertModal").modal("show"); 
					break;
				case 4 : 
					$("#alertModalLabel").html("ปัจจุบันมีการล็อคอินซ้อนอยู่ หรือ คุณไม่ได้ล็อกอินเข้าสู่ระบบอย่างถูกต้อง  ระบบจะทำการ reset ข้อมูลใหม่อีกครั้งและพร้อมเข้าใช้งานทันที");
					$("#alertModal").modal("show"); 
					break;
				case 5 : 
					$("#alertModalLabel").html("บัญชีนี้ยังไม่ได้ถูกยืนยันกรุณายืนยันก่อน");
					$("#alertModal").modal("show"); 
					break;
				case 6 : 
					$("#alertModalLabel").html("คุณไม่มีสิทธเข้าใช้งานหน้านี้");
					$("#alertModal").modal("show");
					break;
				case 99 : 
 					$("#alertModalLabel").html("ดำเนินการออกจากระบบอย่างปลอดภัยแล้ว");
					$("#alertModal").modal("show");
					break;
			}			

	});

		
');
?>



<?php
	/* $this->headScript()	-> pointer end of html for include script files (JS) */
	/* reverse order because of prepend! */
	echo $this->headScript()
	->prependFile($this->baseUrl('js/bootstrap.js'))
	->prependFile($this->baseUrl('js/jquery-1.9.0.js'));
	/**/
	?>
	<?php 
	$this->headScript()
		->appendScript('
			$(document).ready(function () {
				$("#myTab a").click(function (e) {
					e.preventDefault()
					$(this).tab("show")
				})
			});
				 
		');
	?>
</body>
</html>
