	<?php
/**
 * Global layout
 *
 * handle all outer content for all view
 *
 * @copyright  802 Digital Media Co. Ltd.
 * @since      File available since Release 1.0
 */
?>
<?php 
/* Initialize specification standard for this page [Bootstrap.php] */
/* IMPORTANT! -> set up every time */
echo $this->doctype();
/**/
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headMeta(); ?>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<?php
	/* print html title string and avoid cross-site scripting attack */
	/* $this->headTitle()	-> pointer on html head title */
	/* $this->escape()		-> avoid cross-site scripting attack (every time when you print out)*/
	/* $this->translate()	-> translate variable to text string */
	//echo $this->headTitle($this->escape($this->translate('ttl_application')));
	echo $this->headTitle($this->escape('Warehouse Management System'));
	/**/
	?>
	<base
		href="<?php
	        if (empty($_SERVER['HTTPS'])) {
	            echo 'http://';
	        } else {
	            echo 'https://';
	        }
	        /* $this->baseUrl()		-> declare base url default or start directory path */
	        echo $_SERVER['HTTP_HOST'].$this->baseUrl();
	        /**/
	        ?>" />
	<link rel="shortcut icon"
		href="<?php echo $this->baseUrl('images/icon/favicon-icon.ico'); ?>" />
	<link rel="apple-touch-icon-precomposed" sizes="512x512"
		href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
	<!--
	    	iPhone and iPad Shortcuts
	    	For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: 57x57
	    	For first-generation iPad: 72x72
	    	For iPhone 4 with high-resolution Retina display: 114x114
		-->
	<!--
	    	<link rel="apple-touch-icon" href="<?php // echo $this->baseUrl('images/apple-touch-icon.png'); ?>" />
		    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
		    <link rel="apple-touch-icon-precomposed" sizes="512x512" href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
		-->
	<?php
	/* $this->headLink()-> pointer on html head link for style sheet declare (CSS) */
	echo $this->headLink()
	->appendStylesheet($this->baseUrl('css/jquery-ui.css'))
	->appendStylesheet($this->baseUrl('css/bootstrap.css'))
	->appendStylesheet($this->baseUrl('css/font-awesome.css'))
	->appendStylesheet($this->baseUrl('css/select2.css'))
	->appendStylesheet($this->baseUrl('css/style.css'))
	->appendStylesheet($this->baseUrl('css/parsley.css'))
	->appendStylesheet($this->baseUrl('css/jquery.dataTables.css'));
	/* define browser */
	// ->appendStylesheet($this->baseUrl('css/ie.css'), null, 'gte IE 7')
	/**/
	?>

</head>
<body>
	
	
	<div id="layout" class="container" style="background-color: #DDDDFF; height: 570px; width: 1200px; margin-top: 25px;
	background-image: url('../images/login_background_3.jpg');
	background-size: 100%;
">
	<div id="index" style="padding-top: 52px;">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-center">
				<div class="well" style="background-color:#F4C747;">
					<div style="position: relative; top: 0px; left: 160px;
 						width: 200px; height: 60px;
						background-size: 100%;
						">
					</div>
	
	
	<form data-parsley-validate class="form-horizontal" id="testForm"
		name="testForm" method="post"
		action="<?php
		
		echo $this->url ( array (
				'controller' => 'system',
				'action' => 'send-reset-password' 
		), null, true );
		?>"
		enctype="application/x-www-form-urlencoded">
		<fieldset>

			<!-- Form Name -->
			<div class="form-group">
				<label class="col-md-5 control-label" for="email">กรุณากรอกอีเมลล์ที่ใช้ในการสมัครสมาชิกของท่าน</label>
				<div class="col-md-5">
					<input id="email" name="email" class="form-control input-md"
						type="text" maxlength='50' Value=""
						required
						data-parsley-type="email"
						data-parsley-length="[0, 50]"
						data-parsley-length-message="email มีความยาวได้มากสุด 50 ตัวอักษร" 
						 />

				</div>
			</div>
			
			
						<!-- Button (Double) -->
			<div class="form-group">
				<label class="col-md-3 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-back btn-danger" type="button"
						onclick="window.location='<?php
						
						echo $this->url ( array (
								'controller' => 'index',
								'action' => 'index' 
						), null, true );
						?>';">ย้อนกลับ</button>
					<button class="btn btn-success" type="submit">
						<span class="glyphicon glyphicon-ok"></span> ยืนยัน
					</button>
				</div>
			</div>
		</fieldset>
		<div class=col-md-4></div>

	</form>

	<?php
	/* $this->headScript()	-> pointer end of html for include script files (JS) */
	/* reverse order because of prepend! */
	echo $this->headScript()
	->prependFile($this->baseUrl('js/bootstrap.js'))
	->prependFile($this->baseUrl('js/parsley.min.js'))
	->prependFile($this->baseUrl('js/jquery-1.9.0.js'));
	
	/**/
	?>
	<?php 
	$this->headScript()
		->appendScript('
			$(document).ready(function () {
				$("#myTab a").click(function (e) {
					e.preventDefault()
					$(this).tab("show")
				})
			});
				 
		');
	?>
</body>
</html>
	