
<?php

// set data default variable
$iFlashMsg = 0;
$sFirstname	= $this->sFirstName;
$sLastname  = $this->sLastName;
$sAddress	= $this->sAddress;
$sEmail		= $this->sEmail;
$sTelNumber	= $this->sTelNumber;




// check validation callback
if (count ( $this->aFlashMsg ) > 0) {
	$aFlashMsg 				= $this->aFlashMsg;
	if(isset($aFlashMsg[0]['flashStatus']))
		$iFlashMsg = $aFlashMsg [0] ['flashStatus'];
}

?>


<input type="hidden" id="flash_msg" name="flash_msg"
		value="<?php echo $iFlashMsg; ?>">

	<form data-parsley-validate class="form-horizontal" id="testForm"
		name="testForm" method="post"
		action="<?php
		
		echo $this->url ( array (
				'controller' => 'system',
				'action' => 'edit-profile' 
		), null, true );
		?>"
		enctype="application/x-www-form-urlencoded">
		<fieldset>

			<!-- Form Name -->
			<legend class="text-center">แก้ไขข้อมูลส่วนตัว</legend>

			
			<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="newPassword">รหัสผ่านใหม่</label>
				<div class="col-md-4">
					<input id="newPassword" name="newPassword" class="form-control input-md"
						type="password" maxlength='20' 
						data-parsley-length="[0, 20]"
						data-parsley-length-message="password ต้องมีความยาวระหว่าง 8-20 ตัวอักษร" />

				</div>
			</div>

			<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="newPasswordConfirm">ยืนยันรหัสผ่านใหม่</label>
				<div class="col-md-4">
					<input id="newPasswordConfirm" name="newPasswordConfirm"
						class="form-control input-md" type="password" maxlength='20'
						 data-parsley-length="[0, 20]"
						data-parsley-equalto="#newPassword"
						data-parsley-length-message="password ต้องมีความยาวระหว่าง 8-20 ตัวอักษร"
						data-parsley-equalto-message="password ไม่ตรงกัน" />

				</div>
			</div>
			
		
			<div class="form-group">
				<label class="col-md-4 control-label" for="firstname">ชื่อจริง</label>
				<div class="col-md-4">
					<input id="firstname" name="firstname"
						class="form-control input-md" type="text" maxlength='30'
						Value="<?php echo $sFirstname ?>" required
						data-parsley-length="[1, 30]"
						data-parsley-length-message="firstname มีความยาวได้มากสุด 30 ตัวอักษร" />

				</div>
			</div>

			<div class="form-group">
				<label class="col-md-4 control-label" for="lastname">นามสกุล</label>
				<div class="col-md-4">
					<input id="lastname" name="lastname" class="form-control input-md"
						type="text" maxlength='30' Value="<?php echo $sLastname ?>"
						data-parsley-type="alphanum"
						required data-parsley-length="[1, 30]"
						data-parsley-length-message="lastname มีความยาวได้มากสุด 30 ตัวอักษร" />

				</div>
			</div>





			<div class="form-group">
				<label class="col-md-4 control-label" for="description">ที่อยู่</label>
				<div class="col-md-4">
					<textarea id="address" name="address" class="form-control" row="3"
						style="resize: none;"
						required data-parsley-length="[1, 250]"
						data-parsley-length-message="address มีความยาวได้มากสุด 250 ตัวอักษร"
						required 
						><?php echo $sAddress ?></textarea>
				</div>
			</div>

			
			<label class="col-md-4 control-label" for="country">ประเทศ</label>
			<div class="col-md-2">
				<select id="country" name="country" class="form-control">
					<option value="Thailand">Thailand</option>
				</select>
			</div>
			<div class="row">
				<div class="col-md-12">&nbsp</div>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label" for="telnumber">เบอร์โทรศัพท์</label>
				<div class="col-md-4">
					<input id="telnumber" name="telnumber"
						class="form-control input-md" type="text" maxlength='20'
						Value="<?php echo $sTelNumber ?>" required
						data-parsley-type="digits"
						data-parsley-type-message="ตัวเลขเท่านั้น"
						data-parsley-length="[1, 10]"
						
						data-parsley-length-message="เบอร์โทรศัพท์ยาวได้แค่ 1-10 ตัวอักษรเท่านั้น" />

				</div>
			</div>

			<div class="form-group">
				<label class="col-md-4 control-label" for="email">อีเมลล์</label>
				<div class="col-md-4">
					<input id="email" name="email" class="form-control input-md"
						type="text" maxlength='50' Value="<?php echo $sEmail ?>"
						required
						data-parsley-type="email"
						data-parsley-length="[0, 50]"
						data-parsley-length-message="email มีความยาวได้มากสุด 50 ตัวอักษร" 
						 />

				</div>
			
			</div>
			
				<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="password">ใส่รหัสผ่านเพื่อยืนยัน</label>
				<div class="col-md-4">
					<input id="password" name="password" class="form-control input-md"
						type="password" maxlength='20' required
						data-parsley-length="[8, 20]"
						data-parsley-length-message="password ต้องมีความยาวระหว่าง 8-20 ตัวอักษร" />

				</div>
			</div>
			
			
		

			<br>
			<!-- Button (Double) -->
			<div class="form-group">
				<label class="col-md-5 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-back btn-danger" type="button"
						onclick="window.location='<?php
						
						echo $this->url ( array (
								'controller' => 'index',
								'action' => 'product-list' 
						), null, true );
						?>';">ย้อนกลับ</button>
					<button class="btn btn-success" type="submit">
						<span class="glyphicon glyphicon-ok"></span> ยืนยัน
					</button>
				</div>
			</div>
		</fieldset>
		<div class=col-md-4></div>

	</form>

	<div class="modal fade" id="alertModal" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header text-center">
					<h4 class="modal-title" id="alertModalLabel">default</h4>
				</div>
				<div class="modal-body text-center">
					<button type="button" class="btn btn-default" data-dismiss="modal">ตกลง</button>
				</div>
			</div>
		</div>
	</div>

<?php
$this->headScript ()->appendScript ( '

		var flash_msg;


		$(document).ready(function () {

	
			// get flash messenger value
			flash_msg = $("#flash_msg").val();
		
			switch(parseInt(flash_msg)) {
				case 905 :
					$("#alertModalLabel").html("รูปแบบของ password ต้องประกอบด้วยตัวเลข ตัวพิมพ์ใหญ่ และตัวพิมพ์เล็กอย่างน้อย 1 ตัวอักษร");
					$("#alertModal").modal("show");
					break;

				case 906 :
					$("#alertModalLabel").html("ชื่อต้องเป็นตัวอักษรเท่านั้น");
					$("#alertModal").modal("show");
					break;

				case 907 :
					$("#alertModalLabel").html("นามสกุลต้องเป็นตัวอักษรเท่านั้น");
					$("#alertModal").modal("show");
					break;

				case 908 :
					$("#alertModalLabel").html("ที่อยู่ต้องเป็นภาษาอังกฤษ หรือ , และ . เท่านั้น");
					$("#alertModal").modal("show");
					break;
				case 901 :
					$("#alertModalLabel").html("กรุณาใส่ข้อมูลให้ครบ");
					$("#alertModal").modal("show");
					break;
				case 898 :
					$("#alertModalLabel").html("Password ไม่ตรงกัน");
					$("#alertModal").modal("show");
					break;
				case 897 :
					$("#alertModalLabel").html("email นี้ถูกใช้งานแล้ว");
					$("#alertModal").modal("show");
					break;
				case 895 :
					$("#alertModalLabel").html("รหัสยืนยันผิด");
					$("#alertModal").modal("show");
					break;
				case 1000 :
					$("#alertModalLabel").html("แก้ไขข้อมูลสำเร็จ");
					$("#alertModal").modal("show");
					break;

			}
		});

		
' );
?>


</body>
