<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h3>ผลการค้นหาล่าสุด</h3></div>
<div class="col-md-4">&nbsp</div>
</div>

<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h2>ตุ๊กตาโทโทโร่ง่วงนอน</h2></div>
<div class="col-md-4">&nbsp</div>
</div>

<div class="row">
<div class="col-md-2">&nbsp</div>
<div class="col-md-8"><h4>ราคา 450.25บาท</h4></div>
<div class="col-md-2">&nbsp</div>
</div>

<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>สินค้าขาย</h4></div>
<div class="col-md-4">&nbsp</div>
</div>

<div class="row">&nbsp</div>
						<div class="link" style="position:absolute;right:30px;">
							<a href="http://www.w3schools.com">ดูข้อมูลสินค้าแบบเต็ม</a>
						</div>

<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-6"><h3>ผลลัพธ์การค้นหา คีย์เวิร์ด - โปเกม่อน - พบ 1 รายการ</h3></div>
<div class="col-md-4">&nbsp</div>
</div>

<div class="col-md-12">&nbsp</div>
				<div class="row">
				<div class="col-md-4">&nbsp</div>
				<div class="form-group">
				<label class="col-md-1 control-label" for="username">ค้นหา</label>
				<div class="col-md-2">
					<input id="username" name="username" 
						class="form-control input-md" type="text" maxlength = '20'			
					/>
				</div>
				</div>
				</div>
				<div class="col-md-12">&nbsp</div>
				<div class="form-group">
				<label class="col-md-5 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-back btn-danger" type="button"
						onclick="window.location='<?php
						
						echo $this->url ( array (
								'controller' => 'setting',
								'action' => 'user-list' 
						), null, true );
						?>';">ย้อนกลับ</button>
					<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-search"></span> ประมูล</button>
				</div>
			</div>
			<div class="col-md-12">&nbsp</div>
			<div class="form-group">
				<label class="col-md-5 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-back btn-danger" type="button"
						onclick="window.location='<?php
						
						echo $this->url ( array (
								'controller' => 'setting',
								'action' => 'user-list' 
						), null, true );
						?>';">ย้อนกลับ</button>
					<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok"></span> ยินยัน</button>
				</div>
			</div>
			<div class="col-md-12">&nbsp</div>
			<div class="col-md-4">&nbsp</div>
			ประเทศไทย     
			<div class="col-md-12">&nbsp</div>
			<div class="col-md-4">&nbsp</div>
			ผู้ซื้อ
			<div class="form-group">
				<label class="col-md-5 control-label" for="submit"></label>
				<div class="col-md-7">
					<button class="btn btn-back btn-danger" type="button"
						onclick="window.location='<?php
						
						echo $this->url ( array (
								'controller' => 'setting',
								'action' => 'user-list' 
						), null, true );
						?>';">ยกเลิก</button>
					<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok"></span> ประมูลอัตโนมัติ</button>
				</div>
			</div>
			
	
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>วิธีการขาย : ประมูล</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>จำนวน : 1ชิ้น</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>ยี่ห้อ : bandai</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>รุ่น : collector editioned</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>ขนาด : สูง 5นิ้ว กว้าง 3.5นิ้ว</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>สภาพสินค้า : 1ปี</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>คุณสมบัติ : น่ารัก เหมาะแก่นักสะสม</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>รูปแบบการชำระเงิน : บัตรเครดิต</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>เหตุผล</h4></div>
<div class="col-md-4">&nbsp</div>
</div>


<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h4>คะแนน</h4></div>
<div class="col-md-4">&nbsp</div>
</div>
	
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h5>เหลื่อเวลาอีก : 1วัน 3ชม</h5></div>
<div class="col-md-4">&nbsp</div>
</div>
		
<div class="row">
<div class="col-md-4">&nbsp</div>
<div class="col-md-4"><h5>จำนวนเงินขั้นต่ำสำหรับประมูล : 1418.2875 บาท</h5></div>
<div class="col-md-4">&nbsp</div>
</div>	


<div class="row">
<div class="col-md-2">&nbsp</div>
<div class="col-md-8"><h2>ให้feedback</h2></div>
<div class="col-md-2">&nbsp</div>
</div>	
<div class="row">
<div class="col-md-2">&nbsp</div>
<div class="col-md-8"><h3>จำนวน 1 ชิ้น ราคา 350.25 บาท</h3></div>
<div class="col-md-2">&nbsp</div>
</div>	