<?php
/**
 * Global layout
 *
 * handle all outer content for all view
 *
 * @copyright 802 Digital Media Co. Ltd.
 * @since File available since Release 1.0
 */
?>
<?php

/* Initialize specification standard for this page [Bootstrap.php] */
/* IMPORTANT! -> set up every time */
echo $this->doctype ();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<?php echo $this->headMeta(); ?>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<?php
/* print html title string and avoid cross-site scripting attack */
/* $this->headTitle() -> pointer on html head title */
/* $this->escape() -> avoid cross-site scripting attack (every time when you print out) */
/* $this->translate() -> translate variable to text string */
// echo $this->headTitle($this->escape($this->translate('ttl_application')));
echo $this->headTitle ( $this->escape ( 'Warehouse Management System' ) );
?>
<base
	href="<?php
	if (empty ( $_SERVER ['HTTPS'] )) {
		echo 'http://';
	} else {
		echo 'https://';
	}
	/* $this->baseUrl() -> declare base url default or start directory path */
	echo $_SERVER ['HTTP_HOST'] . $this->baseUrl ();
	?>" />
<link rel="shortcut icon"
	href="<?php echo $this->baseUrl('images/icon/favicon-icon.ico'); ?>" />
<link rel="apple-touch-icon-precomposed" sizes="512x512"
	href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
<!--
iPhone and iPad Shortcuts
For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: 57x57
For first-generation iPad: 72x72
For iPhone 4 with high-resolution Retina display: 114x114
-->
<!--
<link rel="apple-touch-icon" href="<?php // echo $this->baseUrl('images/apple-touch-icon.png'); ?>" />
<link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
<link rel="apple-touch-icon-precomposed" sizes="512x512" href="<?php echo $this->baseUrl('images/icon/zbv.png'); ?>" />
-->
<?php
/* $this->headLink()-> pointer on html head link for style sheet declare (CSS) */
echo $this->headLink ()->appendStylesheet ( $this->baseUrl ( 'css/jquery-ui.css' ) )->appendStylesheet ( $this->baseUrl ( 'css/bootstrap.css' ) )->appendStylesheet ( $this->baseUrl ( 'css/font-awesome.css' ) )->appendStylesheet ( $this->baseUrl ( 'css/select2.css' ) )->appendStylesheet ( $this->baseUrl ( 'css/style.css' ) )->appendStylesheet ( $this->baseUrl ( 'css/jquery.dataTables.css' ) );
/* define browser */
// ->appendStylesheet($this->baseUrl('css/ie.css'), null, 'gte IE 7')
?>

</head>


<body>
<?php
$bid = 0;
$banlist = $this->aBannedUserId;
//Zend_Debug::dump($this->aBannedUserId );
?>
	<br />
	<p align="center">
		<b>ยกเลิกการจำกัดสิทธิ์สมาชิก</b>
	</p>
	<style>
table {
	width: 60%;
	padding: 15px;
}

td.left {
	width: 5%;
	padding: 15px;
}

td.center {
	width: 40%;
	padding: 15px;
}

td.right {
	width: 5%;
	padding: 15px;
}
</style>
	<table align="center" border=1>
		<tr>
			<td class="left">UserID</td>
			<td class="center">Username</td>
			<th class="right"></th>
		</tr>
		
		<?php for($i = 0; $i < sizeof($banlist, 0); $i++){ ?>
					 
		<tr>
			<td class="left"><?php echo $banlist[$i][0];?></td>
			<td class="center"> <?php echo $banlist[$i][1];?></td>
			<td class="right"><div class="col-md-4">
					<div clss="buttonBuyout">
						<form id="unbanForm" name="unbanForm"
							action="<?php
			echo $this->url ( array (
					'controller' => 'admin',
					'action' => 'unban',
					'bid' => $banlist [$i] [0] 
			), null, true );
			?>"
							enctype="application/x-www-form-urlencoded" method="post">
							<input type="hidden" name="sUsername" class="input-block-level"
								placeholder="Username" required />
							<button class="btn btn-success" type="submit">
								<span class="glyphicon glyphicon-ok"></span>ยกเลิกการระงับสิทธิ์
							</button>
						</form>
					</div>
				</div></td>

		</tr>
		<?php }?>
		
		
		
	</table>



</body>


<?php
/* $this->headScript() -> pointer end of html for include script files (JS) */
/* reverse order because of prepend! */
echo $this->headScript ()->prependFile ( $this->baseUrl ( 'js/bootstrap.js' ) )->prependFile ( $this->baseUrl ( 'js/jquery-1.9.0.js' ) );
?>
<?php

$this->headScript ()->appendScript ( '
$(document).ready(function () {
$("#myTab a").click(function (e) {
e.preventDefault()
$(this).tab("show")
})
});

');
?>